### ISSUE TITLE
Cannot build on my machine

### ISSUE THREAD

**Issue by simlevesque** [yvbbrjdr/i3lock-fancy-rapid#2]
Here's the output:
`gcc -lX11 -fopenmp i3lock-fancy-rapid.o lodepng.o -o i3lock-fancy-rapid`
`i3lock-fancy-rapid.o: In function 'main':`
`i3lock-fancy-rapid.c:(.text.startup+0x5f): undefined reference to 'XOpenDisplay'`
`i3lock-fancy-rapid.c:(.text.startup+0x71): undefined reference to 'XDefaultRootWindow'`
`i3lock-fancy-rapid.c:(.text.startup+0x8d): undefined reference to 'XGetWindowAttributes'`
`i3lock-fancy-rapid.c:(.text.startup+0xdd): undefined reference to 'XGetImage'`
`i3lock-fancy-rapid.c:(.text.startup+0x194): undefined reference to 'XDestroyWindow'`
`i3lock-fancy-rapid.c:(.text.startup+0x19c): undefined reference to 'XCloseDisplay'`
`collect2: error: ld returned 1 exit status`
`Makefile:7: recipe for target 'i3lock-fancy-rapid' failed`
`make: *** [i3lock-fancy-rapid] Error 1`

I'm on Ubuntu 17.10. libx11-dev is installed.

**Comment by yvbbrjdr** [comment]
Thank you for your report. This bug is fixed in 7c655bb.
