### ISSUE TITLE
Pixelation

### ISSUE THREAD

**Issue by matt1003** [yvbbrjdr/i3lock-fancy-rapid#3]
Is it possible to do pixelation rather then blurring?

**Comment by yvbbrjdr** [comment]
It's possible. Instead of applying a box filter on the image, we can calculate the average color of the pixels in a square and set every pixel in that square to be the average color.

**Comment by matt1003** [comment]
That would be awesome. i3lock-fancy still takes 2 to 3 seconds to pixelate, which is far too long.

**Comment by yvbbrjdr** [comment]
@matt1003 The feature is merged!
