### ISSUE TITLE
[Arch] i3lock: Unrecognized option '--indicator'

### ISSUE THREAD

**Issue by dotinspace** [yvbbrjdr/i3lock-fancy-rapid#5]
When running `i3lock-fancier-rapid 5 3` in terminal, I am seeing i3lock error, that the `--indicator` option is not recognized. Any suggestions?

**Comment by yvbbrjdr** [comment]
What version of `i3lock` are you running?

**Comment by dotinspace** [comment]
2.11.1

**Comment by yvbbrjdr** [comment]
This is strange. There is nowhere in the code that calls `i3lock --indicator`.

**Comment by dotinspace** [comment]
Hmm... well, then I dunno. Not a problem anymore here, switched to XMonad. Thanks for getting back to me, though. Closing this.
