### ISSUE TITLE
I3lock-fancy-rapid does not validate arguments

### ISSUE THREAD

**Issue by deltaxflux** [yvbbrjdr/i3lock-fancy-rapid#9]
### Summary

Hey yvbbrjdr,
I3lock-fancy-rapid does not validate arguments. If you set an negative radius or time strange things happen.

### Steps to reproduce
./i3lock-fancy-rapid -x -y where x,y >0

### Solution
Check if radius or time are >=0.

Regards,

deltaxflux

**Comment by yvbbrjdr** [comment]
Fixed! Thanks!
